### ISSUE TITLE
Linker fails XXXX already defined in XXXX.obj

### ISSUE THREAD

**Issue by liquidzym** [roymacdonald/ofxDLib#7]
build with vs2015,any ideas? cheers

ofApp.obj : error LNK2005: "float __cdecl ofxDLib::trackingDistances(class ofRectangle const &,class ofRectangle const &)" (?trackingDistances@ofxDLib@@YAMABVofRectangle@@0@Z) already defined in  main.obj 
1>ofApp.obj : error LNK2005: "float __cdecl ofxDLib::trackingDistances(class ofVec2f const &,class ofVec2f const &)" (?trackingDistances@ofxDLib@@YAMABVofVec2f@@0@Z) already defined in  main.obj 
1>FaceTracker.obj : error LNK2005: "float __cdecl ofxDLib::trackingDistances(class ofRectangle const &,class ofRectangle const &)" (?trackingDistances@ofxDLib@@YAMABVofRectangle@@0@Z) already defined in  main.obj
1>FaceTracker.obj : error LNK2005: "float __cdecl ofxDLib::trackingDistances(class ofVec2f const &,class ofVec2f const &)" (?trackingDistances@ofxDLib@@YAMABVofVec2f@@0@Z)already defined in  main.obj

**Comment by roymacdonald** [comment]
Hi, I haven't tried it with VS.
dlib is a bit picky. you shouldn´t put the dlib folder in your project, instead it only needs to be added to the includes paths. I will check if I have any luck with it on VS. I'll let you know. 
best!

**Comment by liquidzym** [comment]
hi,thxs,i'm using this addon_config.mk which is from here https://github.com/Ushio/ofxDlibFaceDetector/blob/master/addon_config.mk

**Comment by liquidzym** [comment]
ok,should be as static float trackingDistance

**Comment by roymacdonald** [comment]
@liquidzym how is that? I'm not following. sorry. :/

**Comment by liquidzym** [comment]
since the Tracker is header file only ,i have to put static variable  in order to make it working with vs.

``` c
static float trackingDistance(const ofRectangle& a, const ofRectangle& b) {
        ofVec3f centerA = a.getCenter();
        ofVec3f centerB = b.getCenter();
        return centerA.distance(centerB);
    }

    static float trackingDistance(const ofVec2f& a, const ofVec2f& b) {
        return a.distance(b);
    }
```

**Comment by roymacdonald** [comment]
aha, I see. That's odd anyways. can you PR?
cheers!
