### ISSUE TITLE
Nasty hack to compile on Apple's OSes

### ISSUE THREAD

**Issue by roymacdonald** [roymacdonald/ofxDLib#8]
I came across a really nasty compilation error, for which I couldn't find anything by googling (I didn't try that hard though ;) ). 
For some reason that I don't know or understand, there are several objects named `nil` in dlib's code, like [this.](https://github.com/davisking/dlib/blob/master/dlib/graph_cuts/min_cut.h#L165), which collides with Apple's definition for `nil` which roughly is `#define nil nullptr`. So out of all I tried the only fix was to add the following in my addons [.h files that were bothering](https://github.com/roymacdonald/ofxDLib/blob/master/src/HOGtrainer.h#L18-L22)
```
#if defined(TARGET_OSX) || defined(TARGET_OF_IPHONE) || defined(TARGET_OF_IOS)
#ifdef nil
#undef nil
#endif
#endif
```
This is clearly not a good idea, which could bring even nastier problems.
Has anyone seen this before? know how to fix/overcome it? @bakercp , @genekogan @HalfdanJ @stephanschulz 

On the previous version of this addon, dlibs source files were modified by @stephanschulz, in order to be able to compile. This approach requires patching on every dlib update and will break the apothecary implementation. 

I'm not sure if it would be possible to fix this by using sed and some regex in the apothecary script, maybe it works. I'll give it a try but it is not very elegant.

**Comment by bakercp** [comment]
I think this should be fixed upstream ...

**Comment by roymacdonald** [comment]
@bakercp I also think so. I already opened an issue and made a PR.. hope it gets merged.

**Comment by roymacdonald** [comment]
My PR got merge in dlib. Fixed !

**Comment by bakercp** [comment]
Nice work.
